apiVersion: v1
kind: Service
metadata:
  name: besu-svc
  namespace: hik
spec:
  clusterIP: None  # <--- ESTO lo hace Headless
  selector:
    app: besu
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545