apiVersion: v1
kind: ConfigMap
metadata:
  name: hik-contract-artifacts
  namespace: {{ .Values.global.namespaces.besu }}
data:
  abi.json: {{ .Values.contract.abi | quote }}
  bytecode.txt: {{ .Values.contract.bytecode | quote }}