apiVersion: v1
kind: Secret
metadata:
  name: hik-wallet-keys
  namespace: hik
type: Opaque
stringData:
  HIK_PRIVATE_KEY: "0x925ce0ce9d2a1b33d99af994dfe2ced89a4d15e2b350e08e8767d794c1fc8e5b"
  HIK_RPC_URL: "http://besu-svc:8545"
  HIK_CHAIN_ID: "1337"
  HIK_IPFS_CLUSTER_URL: "http://ipfs-cluster:9094"
  HIK_IPFS_KUBO_URL: "http://ipfs-svc:5001"
  HIK_PUBKEY: "place_ed25519_pubkey_hex_here_or_leave_blank"
  HIK_SLM_ENDPOINT: "http://ollama-service:11434"
  HIK_EMBEDDING_ENDPOINT: "http://embedding-sidecar-service:8000"
  HIK_CONTRACT_ADDRESS: "0x1482405fA693300B8A86B373E6365F999844c067" # "0x87F1FB34BdceB9f68462EA3eC0D94d719fe9b776" "0xE2C57bcF2fACdB9381aD2c0fACb19dEEc8a65cF8" "0x1F0007D79583Abf2C6405668F9c91fE26dc1DeF6"
  HIK_GAS_PRICE: "1000000000"
  HIK_GAS_LIMIT: "500000"
  HIK_EVM_GAS_LIMIT: "500000"
  HIK_ANCHOR_GAS_LIMIT: "500000"
  HIK_L2_TIMEOUT_MS: "1500"
  HIK_L3_TIMEOUT_MS: "50000"
  HIK_OLLAMA_MODEL: "qwen2.5:0.5b"
  HIK_MONGO_URI: "mongodb://root:F83wJXfA4t@hik-mongodb:27017/hik-dashboard?authSource=admin"