apiVersion: v1
kind: Secret
metadata:
  name: hik-wallet-keys
  labels:
    app: hik-sidecar
type: Opaque
stringData:
  HIK_PRIVATE_KEY: {{ .Values.secrets.privateKey | quote }}
  HIK_PUBKEY: {{ .Values.secrets.pubKey | quote }}