apiVersion: v1
kind: Service
metadata:
  name: hik-sp-svc
  namespace: hik
spec:
  type: LoadBalancer
  selector:
    app: hik-stream-proxy
  ports:
    - protocol: TCP
      name: http
      port: 8090
      targetPort: 8090
    - protocol: TCP
      name: rtmp
      port: 1935
      targetPort: 1935