cluster:
  replicaCount: 3
  secret: "hik-ipfs-cluster-secret" # Debe contener el CLUSTER_SECRET para el enjambre

# Configuración de los nodos IPFS (Kubo)
ipfs:
  image: ipfs/kubo:v0.27.0
  storage:
    size: 100Gi
    className: "premium-rwo" # SSD recomendado para performance extrema en HIK

# Configuración del Peer de Cluster
peer:
  image: ipfs/ipfs-cluster:latest

# Aislamiento y Resiliencia (Opcional)
nodes:
  nodeSelector: {}
  tolerations: []
  # Anti-afinidad activada por defecto para HA
  podAntiAffinity:
    type: hard # Evita que dos nodos vivan en el mismo host físico

access:
  nodeSelector:
    tier: access-pool # Nodos para servicios de cara al cliente
  tolerations:
    - key: "service"
      operator: "Equal"
      value: "gateway"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  hpa:
    minReplicas: 2
    maxReplicas: 8