apiVersion: v1
kind: Service
metadata:
  name: hik-explorer-svc
  namespace: hik
spec:
  type: LoadBalancer # O NodePort si estás en una red interna
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: explorer