apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-model-cache
  namespace: hik
spec:
  storageClassName: "standard" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi