apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hik-besu.fullname" . }}-genesis
data:
  genesis-template.json: |-
    {
      "config": {
        "chainId": {{ .Values.global.networkId }},
        "qbft": { "blockperiodseconds": {{ .Values.nodes.blockTime }}, "epochlength": 30000 }
      },
      "gasLimit": "0x1fffffffffffff",
      "alloc": {
        "ADDRESS_PLACEHOLDER": { "balance": "0xAD78EBC5AC6200000" } 
      }
    }