apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hik-besu.fullname" . }}-contract-deployer
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: deployer
        image: node:16-alpine
        env:
          - name: PRIV_KEY
            valueFrom:
              secretKeyRef:
                name: besu-deployer-key
                key: key
        command: ["/bin/sh", "-c"]
        args:
          - |
            npm install ethers@5.7.2
            node -e "
            const { ethers } = require('ethers');
            async function main() {
              const provider = new ethers.providers.JsonRpcProvider('http://besu-internal:8545');
              const wallet = new ethers.Wallet(process.env.PRIV_KEY, provider);
              console.log('Deploying HIK Registry with address:', wallet.address);
              // Lógica de deploy del HIKRegistry.sol...
            }
            main();"
      restartPolicy: OnFailure