apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hik-besu.fullname" . }}-keygen-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hik-besu.fullname" . }}-keygen-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hik-besu.fullname" . }}-keygen-rb
subjects:
- kind: ServiceAccount
  name: {{ include "hik-besu.fullname" . }}-keygen-sa
roleRef:
  kind: Role
  name: {{ include "hik-besu.fullname" . }}-keygen-role
  apiGroup: rbac.authorization.k8s.io