global:
  networkId: 1337

nodes:
  replicaCount: 3
  image: hyperledger/besu:23.4.0
  blockTime: 2
  storage:
    size: 50Gi
    class: premium-rwo
  # Opcionales: Si se comentan o borran, Besu corre en cualquier nodo disponible
  # nodeSelector:
  #   dedicated: blockchain
  # tolerations:
  #   - key: "dedicated"
  #     operator: "Equal"
  #     value: "besu"
  #     effect: "NoSchedule"

contract:
  deploy: true