apiVersion: v1
kind: Service
metadata:
  name: hik-shield-svc
  namespace: hik
spec:
  type: LoadBalancer
  selector:
    app: hik-shield
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080