apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hik-ipfs-access-hpa
  namespace: {{ .Values.global.namespaces.ipfs }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hik-ipfs-access
  minReplicas: {{ .Values.access.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.access.hpa.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Escala cuando la CPU supere el 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # También escala por memoria si el caché se llena