apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-storage
  namespace: hik
spec:
  storageClassName: "standard" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi